### ISSUE TITLE
Does this work for wordpress.com hosted sites? 

### ISSUE THREAD

**Issue by mpvosseller** [wokamoto/wp-basic-auth#8]
Does this plugin work for wordpress.com (dot com) hosted site? 
How does one set the http basic auth username and password?
Should it work with a wordpress.com username and password?

Thanks

**Comment by wokamoto** [comment]
@mpvosseller 
We have not verified that it works on sites hosted on wordpress.com.
The username and password for basic authentication are the same as the username and password of the registered WordPress user.

**Comment by mpvosseller** [comment]
OK. I'm confident I put in my correct wordpress.com credentials so I think the answer is that it does not work. Thanks for getting back to me.
